<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>NBNStockPortal</AssemblyName>
    <Title>NBNStockPortal</Title>
    <Product>NBNStockPortal</Product>
    <Description>NBN Stock Portal is a comprehensive inventory management tool designed for field contractors. It features real-time tracking of serialised hardware, bulk consumable logging, automated E-Waste pipeline management, and monthly CSV reporting.</Description>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NbnStock.Core\NbnStock.Core.csproj" />
  </ItemGroup>
	<Target Name="CopyReadmeToPublish" AfterTargets="Publish">
		<Copy SourceFiles="README.md" DestinationFolder="$(PublishDir)" />
	</Target>
</Project>
